# Python Data Types

Python supports the following built-in data types: lists, sets, dictionaries, and dataframes. We will use them to store and manage data. They can be used to implement your familiar data structures pretty easily. 

You may find the following online tutorials useful: 
<ol>
    <li> <a>https://www.geeksforgeeks.org/</a>, 
    </li>
    <li> <a> https://www.w3schools.com/python/default.asp</a>, 
    </li>
    <li> <a>https://www.tutorialspoint.com/python/index.htm</a>.
    </li>
    </ol>

## Lists

A list is a sequence of items, where some items may be the same and items may also be lists. For example, [] is an empty list, ['a'] is a list of letter a, ['a', 1] is a list, and [[],'b'] is a list. 

<b>List operations:</b> 

<ol>
    <li> list.append(x): Add an item to the end of the list. Equivalent to a[len(a):] = [x].
    </li>
    <li> list.extend(iterable): Extend the list by appending all the items from the iterable. Equivalent to a[len(a):] = iterable.
    </li>
    <li> list.insert(i, x): Insert an item at a given position. The first argument is the index of the element before which to insert, so a.insert(0, x) inserts at the front of the list, and a.insert(len(a), x) is equivalent to a.append(x).
    </li>
    <li> list.remove(x): Remove the first item from the list whose value is equal to x. It raises a ValueError if there is no such item.
    </li>
<li>
list.pop([i]):
Remove the item at the given position in the list, and return it. If no index is specified, a.pop() removes and returns the last item in the list. (The square brackets around the i in the method signature denote that the parameter is optional, not that you should type square brackets at that position. You will see this notation frequently in the Python Library Reference.)
    </li>
<li> list.clear():
Remove all items from the list. Equivalent to del a[:].
    </li>
<li>list.index(x[, start[, end]]):
Return zero-based index in the list of the first item whose value is equal to x. Raises a ValueError if there is no such item.
    
The optional arguments start and end are interpreted as in the slice notation and are used to limit the search to a particular subsequence of the list. The returned index is computed relative to the beginning of the full sequence rather than the start argument.
</li>
<li>list.count(x):
Return the number of times x appears in the list.
    </li>
    <li>
list.sort(*, key=None, reverse=False):
Sort the items of the list in place (the arguments can be used for sort customization, see sorted() for their explanation).
    </li>
<li> list.reverse():
Reverse the elements of the list in place.
    </li>
<li> list.copy():
Return a shallow copy of the list. Equivalent to a[:].
    </li>
    </ol>

In [1]:
fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']
fruits

['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']

In [2]:
fruits.count('apple')

2

In [3]:
fruits.insert(4, 'Fuji apple')
fruits

['orange', 'apple', 'pear', 'banana', 'Fuji apple', 'kiwi', 'apple', 'banana']

In [4]:
fruits.count('tangerine')

0

In [5]:
fruits.index('banana')

3

In [6]:
fruits.index('banana', 4)  # Find next banana starting a position 4

7

In [7]:
fruits.reverse()
fruits

['banana', 'apple', 'kiwi', 'Fuji apple', 'banana', 'pear', 'apple', 'orange']

In [8]:
fruits.append('grape')
fruits

['banana',
 'apple',
 'kiwi',
 'Fuji apple',
 'banana',
 'pear',
 'apple',
 'orange',
 'grape']

In [9]:
fruits.sort()
fruits

['Fuji apple',
 'apple',
 'apple',
 'banana',
 'banana',
 'grape',
 'kiwi',
 'orange',
 'pear']

In [10]:
fruits.pop()

'pear'

In [11]:
fruits

['Fuji apple', 'apple', 'apple', 'banana', 'banana', 'grape', 'kiwi', 'orange']

In [12]:
fruits.pop(3)

'banana'

In [13]:
fruits

['Fuji apple', 'apple', 'apple', 'banana', 'grape', 'kiwi', 'orange']

In [14]:
fruits.clear()
fruits

[]

In [15]:
L = []
L.append([])
L.insert(0, 'a')
L

['a', []]

### Using lists as stacks

A stacks is a list with the same-side in and out: items are pushed in and popped out at the same side. Thus, a stack is a first-in-last-out (FILO) data structure, which is equivalent to last-in-first-out (LIFO).

In [16]:
stack = [3, 4, 5]
stack.append(6)
stack.append(7)
stack

[3, 4, 5, 6, 7]

In [17]:
stack.pop()

7

In [18]:
stack

[3, 4, 5, 6]

In [19]:
stack.pop()

6

In [20]:
stack

[3, 4, 5]

### List comprehensions

List comprehensions provide a concise way to create lists. Common applications are to make new lists where each element is the result of some operations applied to each member of another sequence or iterable, or to create a subsequence of those elements that satisfy a certain condition.

In [21]:
squares = []
for x in range(10):
    squares.append(x**2)
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [22]:
squares = list(map(lambda x: x**2, range(10))) # a different implementation
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [23]:
squares = [x**2 for x in range(10)] # yet another different implementation
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [24]:
[(x, y) for x in [1,2,3] for y in [3,1,4] if x != y]

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]

In [25]:
combs = [] # or equivalently
for x in [1,2,3]:
    for y in [3,1,4]:
        if x != y:
            combs.append((x, y))
combs

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]

In [28]:
vec = [-4, -2, 0, 2, 4]
# create a new list with the values doubled
[x*2 for x in vec]

[-8, -4, 0, 4, 8]

In [29]:
# filter the list to exclude negative numbers
[x for x in vec if x >= 0]

[0, 2, 4]

In [30]:
# apply a function to all the elements
[abs(x) for x in vec]

[4, 2, 0, 2, 4]

In [31]:
# call a method on each element
freshfruit = ['  banana', '  loganberry ', 'passion fruit  ']
[fruit.strip() for fruit in freshfruit]

['banana', 'loganberry', 'passion fruit']

In [32]:
# create a list of 2-tuples like (number, square)
[(x, x**2) for x in range(6)]

[(0, 0), (1, 1), (2, 4), (3, 9), (4, 16), (5, 25)]

In [33]:
# the tuple must be parenthesized, otherwise an error is raised
[x, x**2 for x in range(6)]

SyntaxError: invalid syntax (3265058268.py, line 2)

In [35]:
# flatten a list using a listcomp with two 'for'
vec_ = [[1,2,3], [4,5,6], [7,8,9]]
[num for elem in vec_ for num in elem]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

List comprehensions can contain complex expressions and nested functions:

In [36]:
from math import pi
[str(round(pi, i)) for i in range(1, 12)]

['3.1',
 '3.14',
 '3.142',
 '3.1416',
 '3.14159',
 '3.141593',
 '3.1415927',
 '3.14159265',
 '3.141592654',
 '3.1415926536',
 '3.14159265359']

### Nested list comprehensions

The initial expression in a list comprehension can be any arbitrary expression, including another list comprehension.

In [26]:
matrix = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
]
matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [38]:
matrix[0]

[1, 2, 3, 4]

### Three ways to do transpose

In [39]:
[[row[i] for row in matrix] for i in range(4)] # transposed of matrix

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

In [40]:
# or equivalently
transposed = [] 
for i in range(4):
    transposed.append([row[i] for row in matrix])
transposed

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

In [41]:
# yet another way to do transpose
transposed = []
for i in range(4): 
    # the following 3 lines implement the nested listcomp
    transposed_row = []
    for row in matrix:
        transposed_row.append(row[i])
    transposed.append(transposed_row)
transposed

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

### The zip() function

In the real world, you should prefer built-in functions to complex flow statements. The zip() function would do a great job for doing matrix transpose. 

The zip() function returns a zip object, which is an iterator of tuples where the first item in each passed iterator is paired together, and then the second item in each passed iterator are paired together etc.

In [30]:
matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [27]:
# The simplist implemenation of transpose
list(zip(*matrix)) 

[(1, 5, 9), (2, 6, 10), (3, 7, 11), (4, 8, 12)]

In [43]:
list(zip(matrix[0], matrix[1], matrix[2]))

[(1, 5, 9), (2, 6, 10), (3, 7, 11), (4, 8, 12)]

### The del statement

In [44]:
a = [-1, 1, 66.25, 333, 333, 1234.5]
del a[0]
a

[1, 66.25, 333, 333, 1234.5]

In [45]:
del a[2:4]
a

[1, 66.25, 1234.5]

In [46]:
del a[:]
a

[]

In [47]:
del a # a is removed

In [48]:
a

NameError: name 'a' is not defined

## Tuples and sequences

Lists and strings are two examples of sequence data types. There is also another standard sequence data type: the tuple, which is a sequence of items enclosed by parentheses.

In [49]:
t = 12345, 54321, 'hello!'
t

(12345, 54321, 'hello!')

In [50]:
t[1]

54321

In [51]:
# Tuples may be nested:
u = t, (1, 2, 3, 4, 5)
u

((12345, 54321, 'hello!'), (1, 2, 3, 4, 5))

In [52]:
# Tuples are immutable:
t[0] = 88888

TypeError: 'tuple' object does not support item assignment

In [53]:
# but they can contain mutable objects:
v = ([1, 2, 3], [3, 2, 1])
v

([1, 2, 3], [3, 2, 1])

In [54]:
empty = ()
singleton = 'hello',    # <-- note trailing comma
len(empty)

0

In [55]:
len(singleton)

1

In [56]:
singleton

('hello',)

### Tuple packing

The statement t = 12345, 54321, 'hello!' is an example of tuple packing: the values 12345, 54321 and 'hello!' are packed together in a tuple. 

### Tuple unpacking

The reverse operation is also possible:

In [57]:
x, y, z = t
t

(12345, 54321, 'hello!')

In [58]:
x

12345

In [59]:
y

54321

In [60]:
z

'hello!'

## Sets

A set is an unordered collection with no duplicate elements. Basic uses include membership testing and eliminating duplicate entries. Set objects also support mathematical operations like union, intersection, difference, and symmetric difference.

Curly braces or the set() function can be used to create sets. Note: to create an empty set you have to use set(), not {}; the latter creates an empty dictionary, a data structure that we discuss in the next section.

In [61]:
basket = {'apple', 'orange', 'apple', 'pear', 'orange', 'banana'}
basket

{'apple', 'banana', 'orange', 'pear'}

In [62]:
'orange' in basket                 # fast membership testing

True

In [63]:
'crabgrass' in basket

False

In [64]:
a = set('abracadabra')
b = set('alacazam')
a 

{'a', 'b', 'c', 'd', 'r'}

In [65]:
b

{'a', 'c', 'l', 'm', 'z'}

In [66]:
a | b #union

{'a', 'b', 'c', 'd', 'l', 'm', 'r', 'z'}

In [67]:
a - b #difference

{'b', 'd', 'r'}

In [68]:
a & b #intersection

{'a', 'c'}

In [69]:
a ^ b #exclusive or

{'b', 'd', 'l', 'm', 'r', 'z'}

In [70]:
(a | b) - (a & b) # same as a ^ b

{'b', 'd', 'l', 'm', 'r', 'z'}

In [71]:
a = {x for x in 'abracadabra' if x not in 'abc'}
a

{'d', 'r'}

## Dictionaries

Dictionaries are sometimes found in other languages as “associative memories” or “associative arrays”. Unlike sequences, which are indexed by a range of numbers, dictionaries are indexed by keys, which can be any immutable type; strings and numbers can always be keys. Tuples can be used as keys if they contain only strings, numbers, or tuples; if a tuple contains any mutable object either directly or indirectly, it cannot be used as a key. You can’t use lists as keys, since lists can be modified in place using index assignments, slice assignments, or methods like append() and extend().

It is best to think of a dictionary as a set of key: value pairs, with the requirement that the keys are unique (within one dictionary). A pair of braces creates an empty dictionary: {}. Placing a comma-separated list of key:value pairs within the braces adds initial key:value pairs to the dictionary; this is also the way dictionaries are written on output.

The main operations on a dictionary are storing a value with some key and extracting the value given the key. It is also possible to delete a key:value pair with del. If you store using a key that is already in use, the old value associated with that key is forgotten. It is an error to extract a value using a non-existent key.

Performing list(d) on a dictionary returns a list of all the keys used in the dictionary, in insertion order (if you want it sorted, just use sorted(d) instead). To check whether a single key is in the dictionary, use the in keyword.

In [72]:
tel = {'jack': 4098, 'sape': 4139}
tel['guido'] = 4127
tel

{'jack': 4098, 'sape': 4139, 'guido': 4127}

In [73]:
tel['jack']

4098

In [74]:
del tel['sape']
tel

{'jack': 4098, 'guido': 4127}

In [75]:
tel['irv'] = 4127
tel

{'jack': 4098, 'guido': 4127, 'irv': 4127}

In [76]:
list(tel)

['jack', 'guido', 'irv']

In [77]:
sorted(tel)

['guido', 'irv', 'jack']

In [78]:
'guido' in tel

True

In [79]:
'jack' not in tel

False

### dict() constructor 

It builds dictionaries directly from sequences of key-value pairs:

In [80]:
dict([('sape', 4139), ('guido', 4127), ('jack', 4098)])

{'sape': 4139, 'guido': 4127, 'jack': 4098}

In [81]:
{x: x**2 for x in (2, 4, 6)}

{2: 4, 4: 16, 6: 36}

In [82]:
dict(sape=4139, guido=4127, jack=4098)

{'sape': 4139, 'guido': 4127, 'jack': 4098}

## Pandas data frames

A data frame, supported by Pandas (i.e., not a Python's built-in data type), is a two-dimensional data structure like a table/matix of rows and columns. Widely used in practice, Pandas DataFrame consists of three principal components: data, rows, and columns.

### Create a dataframe using lists

DataFrame can be created using a single list or a list of lists.

In [83]:
import pandas as pd
 
# list of strings
lst = ['Geeks', 'For', 'Geeks', 'is', 'portal', 'for', 'Geeks']
 
df = pd.DataFrame(lst)
df

0
0   Geeks
1     For
2   Geeks
3      is
4  portal
5     for
6   Geeks

### Creat a dataframe using dictionaries

In [84]:
# intialise data of lists.
data = {'Name':['Tom', 'nick', 'krish', 'jack'],
        'Age':[20, 21, 19, 18]}
 
# Create DataFrame
df = pd.DataFrame(data)
df

Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18

### Working with rows and columns

We can perform basic operations on rows/columns including selecting, deleting, adding, and renaming.

In [85]:
# Define a dictionary containing of employee data
data = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Address':['Delhi', 'Kanpur', 'Allahabad', 'Kannauj'],
        'Qualification':['Msc', 'MA', 'MCA', 'PhD']}
 
# Convert the dictionary into DataFrame 
df = pd.DataFrame(data)
df

Name  Age    Address Qualification
0     Jai   27      Delhi           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannauj           PhD

### Row selection

In [96]:
# making data frame from csv file
data = pd.read_csv("nba.csv", index_col ="Name")
data.head(5)

Team  Number Position  Age  Height  Weight  \
Name                                                                  
Avery Bradley  Boston Celtics       0       PG   25   2-Jun     180   
Jae Crowder    Boston Celtics      99       SF   25   6-Jun     235   
John Holland   Boston Celtics      30       SG   27   5-Jun     205   
R.J. Hunter    Boston Celtics      28       SG   22   5-Jun     185   
Jonas Jerebko  Boston Celtics       8       PF   29  10-Jun     231   

                         College     Salary  
Name                                         
Avery Bradley              Texas  7730337.0  
Jae Crowder            Marquette  6796117.0  
John Holland   Boston University        NaN  
R.J. Hunter        Georgia State  1148640.0  
Jonas Jerebko                NaN  5000000.0

In [92]:
# retrieving row by loc method
first = data.loc["Avery Bradley"]
second = data.loc["R.J. Hunter"]
 
print(first, "\n\n\n", second)

Team        Boston Celtics
Number                   0
Position                PG
Age                     25
Height               2-Jun
Weight                 180
College              Texas
Salary           7730337.0
Name: Avery Bradley, dtype: object 


 Team        Boston Celtics
Number                  28
Position                SG
Age                     22
Height               5-Jun
Weight                 185
College      Georgia State
Salary           1148640.0
Name: R.J. Hunter, dtype: object


### Indexing and selecting data

Indexing in pandas data frames means simply selecting particular rows and columns of data from a DataFrame. Indexing could mean selecting all the rows and some of the columns, some of the rows and all of the columns, or some of each of the rows and columns. Indexing can also be known as Subset Selection.

There are three indexing methods: [], .loc, and .iloc.

In [97]:
# retrieving columns by indexing operator [] on column attributes (boldface)
first = data["Age"]
first

Name
Avery Bradley    25
Jae Crowder      25
John Holland     27
R.J. Hunter      22
Jonas Jerebko    29
                 ..
Trey Lyles       20
Shelvin Mack     26
Raul Neto        24
Tibor Pleiss     26
Jeff Withey      26
Name: Age, Length: 457, dtype: int64

In [98]:
# retrieving row by loc method on row attributes (boldface)
first = data.loc["Avery Bradley"]
second = data.loc["R.J. Hunter"]

print(first, "\n\n\n", second)

Team        Boston Celtics
Number                   0
Position                PG
Age                     25
Height               2-Jun
Weight                 180
College              Texas
Salary           7730337.0
Name: Avery Bradley, dtype: object 


 Team        Boston Celtics
Number                  28
Position                SG
Age                     22
Height               5-Jun
Weight                 185
College      Georgia State
Salary           1148640.0
Name: R.J. Hunter, dtype: object


In [99]:
# retrieving rows by iloc method on row index
row2 = data.iloc[3] 

Team        Boston Celtics
Number                  28
Position                SG
Age                     22
Height               5-Jun
Weight                 185
College      Georgia State
Salary           1148640.0
Name: R.J. Hunter, dtype: object

### Working with missing data

Check for missing values using isnull() and notnull(). Fill missing values using fillna(), replace(), and interpolate().

In [100]:
# dictionary of lists
dict = {'First Score':[100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score':[np.nan, 40, 80, 98]}
 
# creating a dataframe from list
df = pd.DataFrame(dict)
 
# using isnull() function  
df.isnull()

First Score  Second Score  Third Score
0        False         False         True
1        False         False        False
2         True         False        False
3        False          True        False

In [101]:
# filling missing value using fillna()  
df.fillna(0)
df

First Score  Second Score  Third Score
0        100.0          30.0          0.0
1         90.0          45.0         40.0
2          0.0          56.0         80.0
3         95.0           0.0         98.0

In [102]:
# dictionary of lists
dict = {'First Score':[100, 90, np.nan, 95],
        'Second Score': [30, np.nan, 45, 56],
        'Third Score':[52, 40, 80, 98],
        'Fourth Score':[np.nan, np.nan, np.nan, 65]}
 
# creating a dataframe from dictionary
df = pd.DataFrame(dict)
df

First Score  Second Score  Third Score  Fourth Score
0        100.0          30.0           52           NaN
1         90.0           NaN           40           NaN
2          NaN          45.0           80           NaN
3         95.0          56.0           98          65.0

In [103]:
# drop rows with at least one Nan value (Null value)
df.dropna()

First Score  Second Score  Third Score  Fourth Score
3         95.0          56.0           98          65.0

### Iterating over rows and columns

We iterate a dataframe like a dictionary.

In [105]:
# dictionary of lists
dict = {'name':["aparna", "pankaj", "sudhir", "Geeku"],
        'degree': ["MBA", "BCA", "M.Tech", "MBA"],
        'score':[90, 40, 80, 98]}
 
# creating a dataframe from a dictionary 
df = pd.DataFrame(dict)
df

name  degree  score
0  aparna     MBA     90
1  pankaj     BCA     40
2  sudhir  M.Tech     80
3   Geeku     MBA     98

In [106]:
# iterating over rows using iterrows() function 
for i, j in df.iterrows():
    print(i, j)
    print()

0 name      aparna
degree       MBA
score         90
Name: 0, dtype: object

1 name      pankaj
degree       BCA
score         40
Name: 1, dtype: object

2 name      sudhir
degree    M.Tech
score         80
Name: 2, dtype: object

3 name      Geeku
degree      MBA
score        98
Name: 3, dtype: object



In [107]:
columns = list(df)
 
for i in columns:
    # printing the third element of the column
    print (df[i][2])

sudhir
M.Tech
80


## Arrays

Python uses Lists for Arrays. To work with arrays in Python you will have to import a library, such as the array or NumPy libraries. 

### Create an array

In [121]:
# Python program to demonstrate
# Creation of Array
 
# importing "array" for array creations
import array as arr
 
# creating an array with integer type
a = arr.array('i', [1, 2, 3])
 
# printing original array
print ("The new created array is:")
for i in range (0, 3):
    print (a[i], end =" ") # end = " " print space without carriage return
print() # print a new line
 
# creating an array with float type
b = arr.array('d', [2.5, 3.2, 3.3])
 
# printing original array
print ("The new created array is:", end =" ")
for i in range (0, 3):
    print (b[i], end =" ")

The new created array is:
1 2 3 
The new created array is: 2.5 3.2 3.3 

### Add an element to an existing array

In [122]:
# Python program to demonstrate
# Adding Elements to a Array
 
# importing "array" for array creations
import array as arr
 
# array with int type
a = arr.array('i', [1, 2, 3])
 
print ("Array before insertion:", end =" ")
for i in range (0, 3):
    print (a[i], end =" ")
print()
 
# inserting array using
# insert() function
a.insert(1, 4)
 
print ("Array after insertion:", end =" ")
for i in (a):
    print (i, end =" ")
print()
 
# array with float type
b = arr.array('d', [2.5, 3.2, 3.3])
 
print ("Array before insertion:", end =" ")
for i in range (0, 3):
    print (b[i], end =" ")
print()
 
# adding an element using append()
b.append(4.4)

print ("Array after insertion:", end =" ")
for i in (b):
    print (i, end =" ")
print()

Array before insertion: 1 2 3 
Array after insertion: 1 4 2 3 
Array before insertion: 2.5 3.2 3.3 
Array after insertion: 2.5 3.2 3.3 4.4 


### Remove elements from an array

In [123]:
# Python program to demonstrate
# Removal of elements in a Array
  
# importing "array" for array operations
import array
  
# initializing array with array values
# initializes array with signed integers
arr = array.array('i', [1, 2, 3, 1, 5])
 
# printing original array
print ("The new created array is: ", end ="")
for i in range (0, 5):
    print (arr[i], end =" ")
 
print ("\r")
 
# using pop() to remove element at 2nd position
print ("The popped element is: ", end ="")
print (arr.pop(2))
 
# printing array after popping
print ("The array after popping is: ", end ="")
for i in range (0, 4):
    print (arr[i], end =" ")
 
print("\r")
 
# using remove() to remove 1st occurrence of 1
arr.remove(1)
 
# printing array after removing
print ("The array after removing is: ", end ="")
for i in range (0, 3):
    print (arr[i], end =" ")

The new created array is: 1 2 3 1 5 
The popped element is: 3
The array after popping is: 1 2 1 5 
The array after removing is: 2 1 5 

### Slice an array

In [124]:
# Python program to demonstrate
# slicing of elements in a Array
 
# importing array module
import array as arr
 
# creating a list
l = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
 
a = arr.array('i', l)
print("Initial Array: ")
for i in (a):
    print(i, end =" ")
 
# Print elements of a range
# using Slice operation
Sliced_array = a[3:8]
print("\nSlicing elements in a range 3-8: ")
print(Sliced_array)
 
# Print elements from a
# pre-defined point to end
Sliced_array = a[5:]
print("\nElements sliced from 5th "
      "element till the end: ")
print(Sliced_array)
 
# Printing elements from
# beginning till end
Sliced_array = a[:]
print("\nPrinting all elements using slice operation: ")
print(Sliced_array)

Initial Array: 
1 2 3 4 5 6 7 8 9 10 
Slicing elements in a range 3-8: 
array('i', [4, 5, 6, 7, 8])

Elements sliced from 5th element till the end: 
array('i', [6, 7, 8, 9, 10])

Printing all elements using slice operation: 
array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])


## Looping techniques

When looping through dictionaries, the key and corresponding value can be retrieved at the same time using the items() method.

In [108]:
knights = {'gallahad': 'the pure', 'robin': 'the brave'}
for k, v in knights.items():
    print(k, v)

gallahad the pure
robin the brave


In [109]:
for i, v in enumerate(['tic', 'tac', 'toe']):
    print(i, v)

0 tic
1 tac
2 toe


In [110]:
questions = ['name', 'quest', 'favorite color']
answers = ['lancelot', 'the holy grail', 'blue']
for q, a in zip(questions, answers):
    print('What is your {0}?  It is {1}.'.format(q, a))

What is your name?  It is lancelot.
What is your quest?  It is the holy grail.
What is your favorite color?  It is blue.


In [111]:
for i in reversed(range(1, 10, 2)): # the first two specifies the range lower and upper bounds; the 3rd for gap
    print(i) 

9
7
5
3
1


In [112]:
basket = ['apple', 'orange', 'apple', 'pear', 'orange', 'banana']
for i in sorted(basket):
    print(i)

apple
apple
banana
orange
orange
pear


In [113]:
basket = ['apple', 'orange', 'apple', 'pear', 'orange', 'banana']
for f in sorted(set(basket)):
     print(f)

apple
banana
orange
pear


In [114]:
import math
raw_data = [56.2, float('NaN'), 51.7, 55.3, 52.5, float('NaN'), 47.8]
filtered_data = []
for value in raw_data:
     if not math.isnan(value):
         filtered_data.append(value)

filtered_data

[56.2, 51.7, 55.3, 52.5, 47.8]